[build-system]
requires =[
    'gensim',
    'numpy',
    'tqdm',
    'spacy>=3.0.5',
    'bokeh',
    'minisom',
    'transformers',
    'sentence-transformers'
]
build-backend = "setuptools.build_meta"